"""
Django settings for staffmanager project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# НАСТРОЙКА БАЗАЫ ДАННЫХ POSTGRESQL ДЛЯ ЗАПУСКА ПРИЛОЖЕНИЯ ИЗ КОНТЕЙНЕРА

from pathlib import Path
from django.conf import settings    # для импорта настроек из settings.py (SECRET_KEY для SimpleJWT)
from import_export.formats.base_formats import CSV, XLSX    # для импорта и экспорта данных в формате CSV и XLSX

from datetime import timedelta                              # для установки времени жизни токена

import os                                                   # для импорта переменных окружения при запуске конейнера в консоли

import psycopg2                                             # для подключения к БД PostgreSQL
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "your_django_secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
# Для production в настройках окружения указать DEBUG=0
DEBUG = os.getenv("DEBUG", "1") == "1"  # В результате DEBUG или True, или False

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1").split()

# 1. Добавляем константу для DjDT, чтобы он понимал - запросы с каких IP адресов надо обрабатывать
INTERNAL_IPS = [
    "127.0.0.1",
]


# Application definition
IMPORT_FORMATS = [CSV, XLSX]
EXPORT_FORMATS = [CSV, XLSX]

INSTALLED_APPS = [
    # Регистрируем приложения учёта персонала и рабочих мест в наcтройках
    "staff",
    "workplaces",
    "staffmanager",
    # Регистрация WYSIWYG-редактора django-ckeditor-5
    "django_ckeditor_5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_extensions",            # команды и утилиы для разработки на Django
    # Добавляем приложение rest_framework
    "rest_framework",               # для работы с API
    "rest_framework.authtoken",      # Для авторизации через токен    
    "djoser",                       # Для авторизации токеном с помощью djoser
#ВАЖНО!!! Приложение Djoser должно быть зарегистрировано ПОСЛЕ django.contrib.auth и rest_framework, 
#чтобы переписать нужные адреса

    "rest_framework_simplejwt",     # для авторизации через токен c SimpleJWT

    'drf_yasg',                     # для генерации документации по API
    'import_export',
    "corsheaders",                          # Для указания разрешенных источников и заголовков запросов
   
    # 2. Добавляем DjDT в список установленных приложений. DjDT must be after 'django.contrib.staticfiles'
#    "debug_toolbar",                #   для отладки, для продакшена закомментировать
    "django_cleanup.apps.CleanupConfig",  # Для физического удаления файлов после удаления ссылок на них в админке или удаления моделей.
    # ВАЖНО! Приложение django_cleanup должно быть последним в списке установленных приложений 
]

# Настройки графики генерации диаграммы моделей утилитой graph_models
GRAPH_MODELS = {
    'all_applications': False,
    'group_models': True,
    'output': 'png',
    'arrow_shape': 'open',
    'fontname': 'Arial',  # Устанавливаем по умолчанию доступный в системе шрифта (исходный шрифт ROBOTO)
    'fontcolor': 'blue',
    'color_scheme': 'pastel1'
}

SWAGGER_USE_COMPAT_RENDERERS = False    # Для подавления предупреждения об изменении формата swagger и redoc (префикс `.` исключён)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication', # # Авторизация через токен c SimpleJWT
    ],
}
# Настройки для авторизации через токен c SimpleJWT - копируем из документации по SimpleJWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
SIMPLE_JWT = {
    # Обязательно импортировать from datetime import timedelta
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=500),      # Время жизни токена
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",                # алгоритм шифрования для формирования подписи
    "SIGNING_KEY": settings.SECRET_KEY,  # секретный ключ для подписи
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),                   # заголовок перед токеном в заголовке запроса для авторизации
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",           # поле, в котором будет передаваться токен
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",       
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=500),        # те же значения времени истечения, что и для access_token 
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=5),     # и refresh_token.

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}
# Настройки CORS разрешения запросов от внешних источников
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CORS_ALLOW_METHODS = [ 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = [ 'Authorization', 'Content-Type', ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",                    # Поле для CORS должно быть первым
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",   # По умолчанию статические файлы (css, js, картинки для интерфейса..)
                                                                # в папке app_name/static/,
                                                                # но удобнее хранить их в спец.папке (например, static_dev.).
                                                                # Для этого в settings.py нужно создать константу STATICFILES_DIRS
    # 3. Добавляем DjDT в слой Middleware в качестве middleware
#    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Должен быть последним, для продакшена закомментировать
]

ROOT_URLCONF = "staffmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",   # Подключен Джанго-шаблонизатор (DjangoTemplates).
                                                                        # Но можно использовать и Jinja2
        "DIRS": [
            BASE_DIR / "templates"
        ],  # 'DIRS': [] поиск шаблонов по умолчанию будет в подпапке templates/app_name в папке приложения
        # или 'DIRS': [BASE_DIR / 'templates'] в указанной папке для хранения шаблонов в папке проекта BASE_DIR/,
        "APP_DIRS": True,  # True - поиск шаблонов в папке приложения после поиска в папке проекта
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "staffmanager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 
""" Если база postgres. Запуск docker-compose_postgres.yml"""
if os.getenv('DATABASE') == 'postgres':
    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SQL_DATABASE', 'StaffManager'),
        'USER': os.getenv('SQL_USER', 'postgres'),
        'PASSWORD': os.getenv('SQL_PASSWORD', 'postgres'),
        'HOST': os.getenv('SQL_HOST', 'db'),  # Имя контейнера с БД db, использовать вместо localhost при развертывании в Docker
        'PORT': os.getenv('SQL_PORT', '5432'),
        }
    }
    """ Если база sqlite3. Запуск docker-compose_postgres.yml"""
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Определим конфигурацию CKEditor-5: включаем режим полного набора инструментов и настраиваем высоту редактора
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 100,
        "width": "auto",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Авторизация
LOGIN_URL = "/admin/login/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [                # Указываются локальные папки для хранения статических файлов, 
    BASE_DIR                        # которые будут тоже использованы для сбора статики.
    / "static_dev",                 # Локальная папка static_dev на уровне проекта для хранения общих 
                                    # для всех django-приложений статических файлов (подапки css, js, img, files..)
                                    # Перед использованием в шаблонах надо загрузить тег {% load static %} в шаблонах
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Путь к папке для собирания и хранения статических файлов 
                                        # из всех Django-приложений, включая папки, указанные в STATICFILES_DIRS

# Загрузка пользовательских файлов
MEDIA_URL = "media/"  # url для загрузки файлов пользователями
MEDIA_ROOT = (
    BASE_DIR / "media"
)  # адрес локальной папки для хранения файлов пользователей

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL = "staff.Staff"
